const LOGIN = "LOGIN";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const FETCH_USER = "FETCH_USER";
const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";

export {LOGIN, LOGIN_SUCCESS, FETCH_USER, FETCH_USER_SUCCESS};
